[package]
name = "res"
version = "0.1.0"
authors = ["Jeron Aldaron Lau <jeron.lau@plopgrizzly.tech>"]
description = "A build-script-dependency for generating resources."
keywords = ["resource", "resources", "generate", "media"]
categories = ["data-structures", "development-tools::build-utils", "multimedia"]
license = "MIT"
documentation = "http://at.plopgrizzly.tech/docs/res"
homepage = "http://at.plopgrizzly.tech/res"
repository = "https://github.com/aldarons-tech/res"
exclude = ["README.md", "res/*", ".gitignore"]

[dependencies]
toml = "0.4.2"
adi_storage = "0.1.0"
utem = "0.1.0"
